### ISSUE TITLE
Firmware update on Windows '&' issue

### ISSUE THREAD

**Issue by ThotAlion** [tinymovr/CANine#2]
Hello,

we tried to update the firmware on Windows 10 using the command line 

`wget -q https://raw.githubusercontent.com/yconst/CANine/main/flash.bat & flash.bat`

But the '&' is not a DOS command. Which batch interpreter to use ? It is not specified in the documentation.

**Comment by yconst** [comment]
You should use `cmd.exe`, then it will work. I'll clarify this in the docs.

**Comment by ThotAlion** [comment]
Thanks :-)
