### ISSUE TITLE
Raise can0 network with Canine on Linux

### ISSUE THREAD

**Issue by ThotAlion** [tinymovr/CANine#3]
We did upgrade the firmware of the CANine dongle.
After plugging the dongle on the robot, no can0 interface appear on 'ifconfig'
Is there a command line to execute to create this network entry ? (like candlelight?) or is it automatic ?
And if we have two dongles, how to differenciate them ? Would you have an example or explain in the doc the process to create such udev rule ?

Thank you for your help,

**Comment by yconst** [comment]
When you mention "upgraded", I assume you mean flashing the Candlelight firmware, correct? Because the firmware hosted in this repo is not compatible with socketcan, it is usb only. 

You can follow the guide in the Canable page: https://canable.io/getting-started.html#alt-firmware

**Comment by ThotAlion** [comment]
No, I mean I wanted to flash the firmware on this repo. I though it was a socketcan.
Therefore, this firmware shall open a /dev/ttyUSBX file ?
Thanks again.

**Comment by yconst** [comment]
It only enumerates as a USB device, there is no serial interface. Currently it is supported by our [fork of the python-can library](https://github.com/tinymovr/python-can) (the `develop` branch). It's not yet tested on Linux (Windows and Macos works), but it should work without an issue. 

You can set `--bustype=canine` for Tinymovr studio to use this protocol. In fact, if you pip install studio from the [main branch](https://github.com/tinymovr/Tinymovr), you'll get the forked python-can library installed automatically.

**Comment by yconst** [comment]
Closing this as inactive
